//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Resources/Scripts/NewInputSystem/PlayerInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInput : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInput"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""c82c9483-3efe-4648-ba04-bf3cd8673e52"",
            ""actions"": [
                {
                    ""name"": ""Scroll"",
                    ""type"": ""PassThrough"",
                    ""id"": ""4fea1266-11b9-4298-addb-8b2d1fa2ac25"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ClickOnOne"",
                    ""type"": ""Button"",
                    ""id"": ""f3117b7d-24e4-4214-86df-e014ce4dfa8a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ClickOnTwo"",
                    ""type"": ""Button"",
                    ""id"": ""ae23ba57-df08-42e7-9cfa-1489061d802e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ClickOnThree"",
                    ""type"": ""Button"",
                    ""id"": ""5f5357ce-fe61-443b-ad93-49d87a5847b8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ClickOnFour"",
                    ""type"": ""Button"",
                    ""id"": ""a38847ce-b733-4872-a2c5-960506714e81"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ClickOnFive"",
                    ""type"": ""Button"",
                    ""id"": ""698696a5-b046-4765-b22d-e3bc20439667"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ClickOnSix"",
                    ""type"": ""Button"",
                    ""id"": ""83ac2e61-8e2c-40ea-a75c-6711f8643dec"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ClickOnSeven"",
                    ""type"": ""Button"",
                    ""id"": ""73487f39-7eb1-4668-8a1b-b6ab8af44e5e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""2b221b47-f5bb-4d7d-a81c-d966f259d4fd"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ClickOnOne"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dc56d7e8-c80a-4171-93e6-ce9217f6a7fe"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ClickOnTwo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""01b5878b-ffad-4a37-9af2-55f136892907"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ClickOnThree"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6a6bc08b-a2c0-4e8a-a94f-1f81824a46b6"",
                    ""path"": ""<Mouse>/scroll/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Scroll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e420d99a-b98d-41ec-ba70-169d04e0c078"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ClickOnFour"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7f523ac7-95b7-4fe7-b28e-ba0bb7be46de"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ClickOnFive"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cea97b4a-6f0a-4159-b4bb-e6d03570fd65"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ClickOnSix"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d70655cb-58df-4b89-b220-62c28a9e8610"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ClickOnSeven"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_Scroll = m_Player.FindAction("Scroll", throwIfNotFound: true);
        m_Player_ClickOnOne = m_Player.FindAction("ClickOnOne", throwIfNotFound: true);
        m_Player_ClickOnTwo = m_Player.FindAction("ClickOnTwo", throwIfNotFound: true);
        m_Player_ClickOnThree = m_Player.FindAction("ClickOnThree", throwIfNotFound: true);
        m_Player_ClickOnFour = m_Player.FindAction("ClickOnFour", throwIfNotFound: true);
        m_Player_ClickOnFive = m_Player.FindAction("ClickOnFive", throwIfNotFound: true);
        m_Player_ClickOnSix = m_Player.FindAction("ClickOnSix", throwIfNotFound: true);
        m_Player_ClickOnSeven = m_Player.FindAction("ClickOnSeven", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private IPlayerActions m_PlayerActionsCallbackInterface;
    private readonly InputAction m_Player_Scroll;
    private readonly InputAction m_Player_ClickOnOne;
    private readonly InputAction m_Player_ClickOnTwo;
    private readonly InputAction m_Player_ClickOnThree;
    private readonly InputAction m_Player_ClickOnFour;
    private readonly InputAction m_Player_ClickOnFive;
    private readonly InputAction m_Player_ClickOnSix;
    private readonly InputAction m_Player_ClickOnSeven;
    public struct PlayerActions
    {
        private @PlayerInput m_Wrapper;
        public PlayerActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Scroll => m_Wrapper.m_Player_Scroll;
        public InputAction @ClickOnOne => m_Wrapper.m_Player_ClickOnOne;
        public InputAction @ClickOnTwo => m_Wrapper.m_Player_ClickOnTwo;
        public InputAction @ClickOnThree => m_Wrapper.m_Player_ClickOnThree;
        public InputAction @ClickOnFour => m_Wrapper.m_Player_ClickOnFour;
        public InputAction @ClickOnFive => m_Wrapper.m_Player_ClickOnFive;
        public InputAction @ClickOnSix => m_Wrapper.m_Player_ClickOnSix;
        public InputAction @ClickOnSeven => m_Wrapper.m_Player_ClickOnSeven;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterface != null)
            {
                @Scroll.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnScroll;
                @Scroll.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnScroll;
                @Scroll.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnScroll;
                @ClickOnOne.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnClickOnOne;
                @ClickOnOne.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnClickOnOne;
                @ClickOnOne.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnClickOnOne;
                @ClickOnTwo.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnClickOnTwo;
                @ClickOnTwo.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnClickOnTwo;
                @ClickOnTwo.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnClickOnTwo;
                @ClickOnThree.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnClickOnThree;
                @ClickOnThree.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnClickOnThree;
                @ClickOnThree.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnClickOnThree;
                @ClickOnFour.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnClickOnFour;
                @ClickOnFour.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnClickOnFour;
                @ClickOnFour.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnClickOnFour;
                @ClickOnFive.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnClickOnFive;
                @ClickOnFive.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnClickOnFive;
                @ClickOnFive.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnClickOnFive;
                @ClickOnSix.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnClickOnSix;
                @ClickOnSix.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnClickOnSix;
                @ClickOnSix.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnClickOnSix;
                @ClickOnSeven.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnClickOnSeven;
                @ClickOnSeven.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnClickOnSeven;
                @ClickOnSeven.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnClickOnSeven;
            }
            m_Wrapper.m_PlayerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Scroll.started += instance.OnScroll;
                @Scroll.performed += instance.OnScroll;
                @Scroll.canceled += instance.OnScroll;
                @ClickOnOne.started += instance.OnClickOnOne;
                @ClickOnOne.performed += instance.OnClickOnOne;
                @ClickOnOne.canceled += instance.OnClickOnOne;
                @ClickOnTwo.started += instance.OnClickOnTwo;
                @ClickOnTwo.performed += instance.OnClickOnTwo;
                @ClickOnTwo.canceled += instance.OnClickOnTwo;
                @ClickOnThree.started += instance.OnClickOnThree;
                @ClickOnThree.performed += instance.OnClickOnThree;
                @ClickOnThree.canceled += instance.OnClickOnThree;
                @ClickOnFour.started += instance.OnClickOnFour;
                @ClickOnFour.performed += instance.OnClickOnFour;
                @ClickOnFour.canceled += instance.OnClickOnFour;
                @ClickOnFive.started += instance.OnClickOnFive;
                @ClickOnFive.performed += instance.OnClickOnFive;
                @ClickOnFive.canceled += instance.OnClickOnFive;
                @ClickOnSix.started += instance.OnClickOnSix;
                @ClickOnSix.performed += instance.OnClickOnSix;
                @ClickOnSix.canceled += instance.OnClickOnSix;
                @ClickOnSeven.started += instance.OnClickOnSeven;
                @ClickOnSeven.performed += instance.OnClickOnSeven;
                @ClickOnSeven.canceled += instance.OnClickOnSeven;
            }
        }
    }
    public PlayerActions @Player => new PlayerActions(this);
    public interface IPlayerActions
    {
        void OnScroll(InputAction.CallbackContext context);
        void OnClickOnOne(InputAction.CallbackContext context);
        void OnClickOnTwo(InputAction.CallbackContext context);
        void OnClickOnThree(InputAction.CallbackContext context);
        void OnClickOnFour(InputAction.CallbackContext context);
        void OnClickOnFive(InputAction.CallbackContext context);
        void OnClickOnSix(InputAction.CallbackContext context);
        void OnClickOnSeven(InputAction.CallbackContext context);
    }
}
